services:
  mock-apis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mockoon_service
    ports:
      - "3002:3002" 
    volumes:
      - ./data:/data:ro
    restart: always