
services:
  postgres_second:
    image: postgres:17.5-alpine
    container_name: ekyc_postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=ekyc
    volumes:
      - ./pgdata_second:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  mock-apis:
    build:
      context: ../mockoon
      dockerfile: Dockerfile
    container_name: mockoon_service
    ports:
      - "3002:3002"
    volumes:
      - ../mockoon/data:/data:ro
    restart: always

  backend_api:
    image: node:20-alpine
    container_name: ekyc_backend_api
    working_dir: /app
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_second
      - mock-apis
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://postgres:sa@postgres_second:5432/ekyc
      - NID_OCR_URL=http://mockoon_service:3002/api/v1/nid/info